--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

-- Started on 2023-11-15 00:04:46

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 222 (class 1259 OID 16422)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16421)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16430)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16429)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16416)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16415)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16436)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16444)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16443)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16435)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16450)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16449)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16508)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16507)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16408)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16407)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16400)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16399)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16536)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 16627)
-- Name: patrol_cpudata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.patrol_cpudata (
    id bigint NOT NULL,
    modes character varying NOT NULL,
    vendor character varying NOT NULL,
    model character varying NOT NULL,
    "CPUs" character varying NOT NULL,
    threads character varying NOT NULL,
    cores_per_socket character varying NOT NULL,
    sockets character varying NOT NULL
);


ALTER TABLE public.patrol_cpudata OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16626)
-- Name: patrol_cpudata_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.patrol_cpudata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.patrol_cpudata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 16643)
-- Name: patrol_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.patrol_logs (
    id bigint NOT NULL,
    date date NOT NULL,
    "time" time without time zone NOT NULL,
    function character varying NOT NULL,
    event character varying NOT NULL
);


ALTER TABLE public.patrol_logs OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 16642)
-- Name: patrol_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.patrol_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.patrol_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16635)
-- Name: patrol_osdata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.patrol_osdata (
    id bigint NOT NULL,
    "OS" character varying NOT NULL,
    description character varying NOT NULL,
    release character varying NOT NULL,
    codename character varying NOT NULL,
    architecture character varying NOT NULL,
    kernel character varying NOT NULL,
    type character varying NOT NULL
);


ALTER TABLE public.patrol_osdata OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16634)
-- Name: patrol_osdata_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.patrol_osdata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.patrol_osdata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4906 (class 0 OID 16422)
-- Dependencies: 222
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- TOC entry 4908 (class 0 OID 16430)
-- Dependencies: 224
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 4904 (class 0 OID 16416)
-- Dependencies: 220
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add o s_info	7	add_os_info
26	Can change o s_info	7	change_os_info
27	Can delete o s_info	7	delete_os_info
28	Can view o s_info	7	view_os_info
29	Can add os info	8	add_osinfo
30	Can change os info	8	change_osinfo
31	Can delete os info	8	delete_osinfo
32	Can view os info	8	view_osinfo
33	Can add os information	9	add_osinformation
34	Can change os information	9	change_osinformation
35	Can delete os information	9	delete_osinformation
36	Can view os information	9	view_osinformation
37	Can add cpu information	10	add_cpuinformation
38	Can change cpu information	10	change_cpuinformation
39	Can delete cpu information	10	delete_cpuinformation
40	Can view cpu information	10	view_cpuinformation
41	Can add os data	11	add_osdata
42	Can change os data	11	change_osdata
43	Can delete os data	11	delete_osdata
44	Can view os data	11	view_osdata
45	Can add cpu data	12	add_cpudata
46	Can change cpu data	12	change_cpudata
47	Can delete cpu data	12	delete_cpudata
48	Can view cpu data	12	view_cpudata
49	Can add info	13	add_info
50	Can change info	13	change_info
51	Can delete info	13	delete_info
52	Can view info	13	view_info
53	Can add test	14	add_test
54	Can change test	14	change_test
55	Can delete test	14	delete_test
56	Can view test	14	view_test
57	Can add logs	15	add_logs
58	Can change logs	15	change_logs
59	Can delete logs	15	delete_logs
60	Can view logs	15	view_logs
\.


--
-- TOC entry 4910 (class 0 OID 16436)
-- Dependencies: 226
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$600000$c6T2YHiN7vjUNn69Loop54$0N2beY6MnORyKsG9OkjpnV8tfzTKLPvXGlWixc6L4mI=	2023-11-13 01:36:05.504953+03	t	admin				t	t	2023-11-13 01:28:08.489776+03
\.


--
-- TOC entry 4912 (class 0 OID 16444)
-- Dependencies: 228
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- TOC entry 4914 (class 0 OID 16450)
-- Dependencies: 230
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- TOC entry 4916 (class 0 OID 16508)
-- Dependencies: 232
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- TOC entry 4902 (class 0 OID 16408)
-- Dependencies: 218
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	patrol	os_info
8	patrol	osinfo
9	patrol	osinformation
10	patrol	cpuinformation
11	patrol	osdata
12	patrol	cpudata
13	patrol	info
14	patrol	test
15	patrol	logs
\.


--
-- TOC entry 4900 (class 0 OID 16400)
-- Dependencies: 216
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2023-11-12 21:12:34.854992+03
2	auth	0001_initial	2023-11-12 21:12:34.917568+03
3	admin	0001_initial	2023-11-12 21:12:34.93325+03
4	admin	0002_logentry_remove_auto_add	2023-11-12 21:12:34.937771+03
5	admin	0003_logentry_add_action_flag_choices	2023-11-12 21:12:34.941232+03
6	contenttypes	0002_remove_content_type_name	2023-11-12 21:12:34.949159+03
7	auth	0002_alter_permission_name_max_length	2023-11-12 21:12:34.953904+03
8	auth	0003_alter_user_email_max_length	2023-11-12 21:12:34.958904+03
9	auth	0004_alter_user_username_opts	2023-11-12 21:12:34.962663+03
10	auth	0005_alter_user_last_login_null	2023-11-12 21:12:34.966915+03
11	auth	0006_require_contenttypes_0002	2023-11-12 21:12:34.967915+03
12	auth	0007_alter_validators_add_error_messages	2023-11-12 21:12:34.971916+03
13	auth	0008_alter_user_username_max_length	2023-11-12 21:12:34.980836+03
14	auth	0009_alter_user_last_name_max_length	2023-11-12 21:12:34.985297+03
15	auth	0010_alter_group_name_max_length	2023-11-12 21:12:34.990299+03
16	auth	0011_update_proxy_permissions	2023-11-12 21:12:34.994178+03
17	auth	0012_alter_user_first_name_max_length	2023-11-12 21:12:34.998179+03
18	sessions	0001_initial	2023-11-12 21:12:35.007411+03
19	patrol	0001_initial	2023-11-13 01:25:46.484928+03
20	patrol	0002_delete_os_info	2023-11-13 02:12:40.0629+03
21	patrol	0002_osinformation	2023-11-13 02:20:35.205361+03
22	patrol	0002_cpuinformation	2023-11-13 17:44:03.761696+03
23	patrol	0002_osdata	2023-11-14 00:31:52.565301+03
24	patrol	0002_cpudata	2023-11-14 00:36:55.158726+03
25	patrol	0003_osdata	2023-11-14 00:37:27.468864+03
26	patrol	0002_cpudata_osdata	2023-11-14 00:46:13.87879+03
27	patrol	0003_logs	2023-11-14 03:13:51.541676+03
\.


--
-- TOC entry 4917 (class 0 OID 16536)
-- Dependencies: 233
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
emke9qfuv0ma5krt6rp5ayvi69kadksk	.eJxVjMsOwiAQRf-FtSFAeQSX7v0GMjMMUjWQlHZl_Hdt0oVu7znnvkSCba1pG7ykOYuz0OL0uyHQg9sO8h3arUvqbV1mlLsiDzrktWd-Xg7376DCqN_alMxBkdM-MrjJG3QKg_KWC-QYfNQqko6WpoKErLNzSBZ8CDhpE0G8P-V5N_4:1r2J3l:q9NyIE3LUXMy5A-QvJNAi657oNHudi_UBf0NrGw6JqA	2023-11-27 01:36:05.506477+03
\.


--
-- TOC entry 4919 (class 0 OID 16627)
-- Dependencies: 235
-- Data for Name: patrol_cpudata; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.patrol_cpudata (id, modes, vendor, model, "CPUs", threads, cores_per_socket, sockets) FROM stdin;
1	32-bit, 64-bit	AuthenticAMD	AMD Ryzen 5 5600H with Radeon Graphics	1	1	1	1
2	32-bit, 64-bit	AuthenticAMD	AMD Ryzen 5 5600H with Radeon Graphics	2	1	2	1
3	32-bit, 64-bit	AuthenticAMD	AMD Ryzen 5 5600H with Radeon Graphics	1	1	1	1
4	32-bit, 64-bit	AuthenticAMD	AMD Ryzen 5 5600H with Radeon Graphics	1	1	1	1
5	32-bit, 64-bit	AuthenticAMD	AMD Ryzen 5 5600H with Radeon Graphics	1	1	1	1
6	32-bit, 64-bit	AuthenticAMD	AMD Ryzen 5 5600H with Radeon Graphics	1	1	1	1
7	32-bit, 64-bit	AuthenticAMD	AMD Ryzen 5 5600H with Radeon Graphics	1	1	1	1
8	32-bit, 64-bit	AuthenticAMD	AMD Ryzen 5 5600H with Radeon Graphics	1	1	1	1
9	32-bit, 64-bit	AuthenticAMD	AMD Ryzen 5 5600H with Radeon Graphics	1	1	1	1
10	32-bit, 64-bit	AuthenticAMD	AMD Ryzen 5 5600H with Radeon Graphics	1	1	1	1
\.


--
-- TOC entry 4923 (class 0 OID 16643)
-- Dependencies: 239
-- Data for Name: patrol_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.patrol_logs (id, date, "time", function, event) FROM stdin;
1	2023-11-14	03:41:27	connection_ssh(request)	ssh connection to host 192.168.1.28
2	2023-11-14	03:53:03	connection_ssh(request)	ssh connection to host 192.168.1.28
3	2023-11-14	03:54:23	connection_ssh(request)	ssh connection to host 192.168.1.28
4	2023-11-14	03:55:09	connection_ssh(request)	ssh connection to host 192.168.1.28
5	2023-11-14	03:56:25	connection_ssh(request)	ssh connection to host 192.168.1.28
6	2023-11-14	03:56:25	connection_ssh(request)	successful connection
7	2023-11-14	03:57:57	connection_ssh(request)	ssh connection to host 192.168.1.28
8	2023-11-14	03:57:57	connection_ssh(request)	successful connection
9	2023-11-14	13:20:27	connection_ssh(request)	connection break
10	2023-11-14	13:20:33	connection_ssh(request)	connection break
11	2023-11-14	13:20:33	connection_ssh(request)	ssh connection to host 192.168.1.28
12	2023-11-14	13:20:33	connection_ssh(request)	successful connection
13	2023-11-14	13:20:33	detect_data_on_host()	send command: lsb_release -i
14	2023-11-14	13:20:33	detect_data_on_host()	detected data: Ubuntu
15	2023-11-14	13:20:33	detect_data_on_host()	send command: lsb_release -d
16	2023-11-14	13:20:33	detect_data_on_host()	detected data: Ubuntu 20.04.6 LTS
17	2023-11-14	13:20:34	detect_data_on_host()	send command: lsb_release -r
18	2023-11-14	13:20:34	detect_data_on_host()	detected data: 20.04
19	2023-11-14	13:20:34	detect_data_on_host()	send command: lsb_release -c
20	2023-11-14	13:20:34	detect_data_on_host()	detected data: focal
21	2023-11-14	13:20:34	detect_data_on_host()	send command: uname -m
22	2023-11-14	13:20:34	detect_data_on_host()	detected data: x86_64
23	2023-11-14	13:20:34	detect_data_on_host()	send command: uname -r
24	2023-11-14	13:20:34	detect_data_on_host()	detected data: 5.15.0-88-generic
25	2023-11-14	13:20:34	detect_data_on_host()	send command: getconf LONG_BIT
26	2023-11-14	13:20:34	detect_data_on_host()	detected data: 64
27	2023-11-14	13:20:34	detect_os_data()	creating an OsData database record
28	2023-11-14	13:20:34	detect()	OS data detection
29	2023-11-14	13:20:34	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU op-mode(s):'
30	2023-11-14	13:20:34	detect_data_on_host()	detected data: 32-bit, 64-bit
31	2023-11-14	13:20:34	detect_data_on_host()	send command: lscpu | grep -m 1 'Vendor ID:'
32	2023-11-14	13:20:34	detect_data_on_host()	detected data: AuthenticAMD
33	2023-11-14	13:20:34	detect_data_on_host()	send command: lscpu | grep -m 1 'Model name:'
34	2023-11-14	13:20:34	detect_data_on_host()	detected data: AMD Ryzen 5 5600H with Radeon Graphics
35	2023-11-14	13:20:34	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU(s):'
36	2023-11-14	13:20:34	detect_data_on_host()	detected data: 1
37	2023-11-14	13:20:34	detect_data_on_host()	send command: lscpu | grep -m 1 'Thread(s) per core:'
38	2023-11-14	13:20:34	detect_data_on_host()	detected data: 1
39	2023-11-14	13:20:34	detect_data_on_host()	send command: lscpu | grep -m 1 'Core(s) per socket:'
40	2023-11-14	13:20:34	detect_data_on_host()	detected data: 1
41	2023-11-14	13:20:34	detect_data_on_host()	send command: lscpu | grep -m 1 'Socket(s):'
42	2023-11-14	13:20:34	detect_data_on_host()	detected data: 1
43	2023-11-14	13:20:34	detect_cpu_info()	creating an CpuData database record
44	2023-11-14	13:20:34	detect()	CPU data detection
45	2023-11-14	13:21:37	connection_ssh(request)	connection break
46	2023-11-14	13:21:42	connection_ssh(request)	connection break
47	2023-11-14	13:21:42	connection_ssh(request)	ssh connection to host 192.168.1.28
48	2023-11-14	13:21:42	connection_ssh(request)	successful connection
49	2023-11-14	13:21:42	detect_data_on_host()	send command: lsb_release -i
50	2023-11-14	13:21:42	detect_data_on_host()	detected data: Ubuntu
51	2023-11-14	13:21:42	detect_data_on_host()	send command: lsb_release -d
52	2023-11-14	13:21:42	detect_data_on_host()	detected data: Ubuntu 20.04.6 LTS
53	2023-11-14	13:21:42	detect_data_on_host()	send command: lsb_release -r
54	2023-11-14	13:21:42	detect_data_on_host()	detected data: 20.04
55	2023-11-14	13:21:42	detect_data_on_host()	send command: lsb_release -c
56	2023-11-14	13:21:42	detect_data_on_host()	detected data: focal
57	2023-11-14	13:21:42	detect_data_on_host()	send command: uname -m
58	2023-11-14	13:21:42	detect_data_on_host()	detected data: x86_64
59	2023-11-14	13:21:42	detect_data_on_host()	send command: uname -r
60	2023-11-14	13:21:42	detect_data_on_host()	detected data: 5.15.0-88-generic
61	2023-11-14	13:21:42	detect_data_on_host()	send command: getconf LONG_BIT
62	2023-11-14	13:21:43	detect_data_on_host()	detected data: 64
63	2023-11-14	13:21:43	detect_os_data()	creating an OsData database record
64	2023-11-14	13:21:43	detect()	OS data detection
65	2023-11-14	13:21:43	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU op-mode(s):'
66	2023-11-14	13:21:43	detect_data_on_host()	detected data: 32-bit, 64-bit
67	2023-11-14	13:21:43	detect_data_on_host()	send command: lscpu | grep -m 1 'Vendor ID:'
68	2023-11-14	13:21:43	detect_data_on_host()	detected data: AuthenticAMD
69	2023-11-14	13:21:43	detect_data_on_host()	send command: lscpu | grep -m 1 'Model name:'
70	2023-11-14	13:21:43	detect_data_on_host()	detected data: AMD Ryzen 5 5600H with Radeon Graphics
71	2023-11-14	13:21:43	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU(s):'
72	2023-11-14	13:21:43	detect_data_on_host()	detected data: 1
73	2023-11-14	13:21:43	detect_data_on_host()	send command: lscpu | grep -m 1 'Thread(s) per core:'
74	2023-11-14	13:21:43	detect_data_on_host()	detected data: 1
75	2023-11-14	13:21:43	detect_data_on_host()	send command: lscpu | grep -m 1 'Core(s) per socket:'
76	2023-11-14	13:21:43	detect_data_on_host()	detected data: 1
77	2023-11-14	13:21:43	detect_data_on_host()	send command: lscpu | grep -m 1 'Socket(s):'
78	2023-11-14	13:21:43	detect_data_on_host()	detected data: 1
79	2023-11-14	13:21:43	detect_cpu_info()	creating an CpuData database record
80	2023-11-14	13:21:43	detect()	CPU data detection
81	2023-11-14	13:22:43	connection_ssh(request)	connection break
82	2023-11-14	13:22:43	connection_ssh(request)	ssh connection to host 192.168.1.28
83	2023-11-14	13:22:43	connection_ssh(request)	successful connection
84	2023-11-14	13:22:43	detect_data_on_host()	send command: lsb_release -i
85	2023-11-14	13:22:43	detect_data_on_host()	detected data: Distributor ID:\tUbuntu\n
86	2023-11-14	13:22:44	detect_data_on_host()	send command: lsb_release -d
87	2023-11-14	13:22:44	detect_data_on_host()	detected data: Description:\tUbuntu 20.04.6 LTS\n
88	2023-11-14	13:22:44	detect_data_on_host()	send command: lsb_release -r
89	2023-11-14	13:22:44	detect_data_on_host()	detected data: Release:\t20.04\n
90	2023-11-14	13:22:44	detect_data_on_host()	send command: lsb_release -c
91	2023-11-14	13:22:44	detect_data_on_host()	detected data: Codename:\tfocal\n
92	2023-11-14	13:22:44	detect_data_on_host()	send command: uname -m
93	2023-11-14	13:22:44	detect_data_on_host()	detected data: x86_64\n
94	2023-11-14	13:22:44	detect_data_on_host()	send command: uname -r
95	2023-11-14	13:22:44	detect_data_on_host()	detected data: 5.15.0-88-generic\n
96	2023-11-14	13:22:44	detect_data_on_host()	send command: getconf LONG_BIT
97	2023-11-14	13:22:44	detect_data_on_host()	detected data: 64\n
98	2023-11-14	13:22:44	detect_os_data()	creating an OsData database record
99	2023-11-14	13:22:44	detect()	OS data detection
100	2023-11-14	13:22:44	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU op-mode(s):'
101	2023-11-14	13:22:44	detect_data_on_host()	detected data: CPU op-mode(s):                     32-bit, 64-bit\n
102	2023-11-14	13:22:44	detect_data_on_host()	send command: lscpu | grep -m 1 'Vendor ID:'
103	2023-11-14	13:22:44	detect_data_on_host()	detected data: Vendor ID:                          AuthenticAMD\n
104	2023-11-14	13:22:44	detect_data_on_host()	send command: lscpu | grep -m 1 'Model name:'
105	2023-11-14	13:22:44	detect_data_on_host()	detected data: Model name:                         AMD Ryzen 5 5600H with Radeon Graphics\n
106	2023-11-14	13:22:44	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU(s):'
107	2023-11-14	13:22:44	detect_data_on_host()	detected data: CPU(s):                             1\n
108	2023-11-14	13:22:44	detect_data_on_host()	send command: lscpu | grep -m 1 'Thread(s) per core:'
109	2023-11-14	13:22:44	detect_data_on_host()	detected data: Thread(s) per core:                 1\n
110	2023-11-14	13:22:44	detect_data_on_host()	send command: lscpu | grep -m 1 'Core(s) per socket:'
111	2023-11-14	13:22:44	detect_data_on_host()	detected data: Core(s) per socket:                 1\n
112	2023-11-14	13:22:44	detect_data_on_host()	send command: lscpu | grep -m 1 'Socket(s):'
113	2023-11-14	13:22:44	detect_data_on_host()	detected data: Socket(s):                          1\n
114	2023-11-14	13:22:44	detect_cpu_info()	creating an CpuData database record
115	2023-11-14	13:22:44	detect()	CPU data detection
116	2023-11-14	13:23:06	connection_ssh(request)	connection break
117	2023-11-14	13:23:11	connection_ssh(request)	connection break
118	2023-11-14	13:23:11	connection_ssh(request)	ssh connection to host 192.168.1.28
119	2023-11-14	13:23:12	connection_ssh(request)	successful connection
120	2023-11-14	13:23:12	detect_data_on_host()	send command: lsb_release -i
121	2023-11-14	13:23:12	detect_data_on_host()	detected data: Distributor ID:\tUbuntu\n
122	2023-11-14	13:23:12	detect_data_on_host()	send command: lsb_release -d
123	2023-11-14	13:23:12	detect_data_on_host()	detected data: Description:\tUbuntu 20.04.6 LTS\n
124	2023-11-14	13:23:12	detect_data_on_host()	send command: lsb_release -r
125	2023-11-14	13:23:12	detect_data_on_host()	detected data: Release:\t20.04\n
126	2023-11-14	13:23:12	detect_data_on_host()	send command: lsb_release -c
127	2023-11-14	13:23:12	detect_data_on_host()	detected data: Codename:\tfocal\n
128	2023-11-14	13:23:12	detect_data_on_host()	send command: uname -m
129	2023-11-14	13:23:12	detect_data_on_host()	detected data: x86_64\n
130	2023-11-14	13:23:12	detect_data_on_host()	send command: uname -r
131	2023-11-14	13:23:12	detect_data_on_host()	detected data: 5.15.0-88-generic\n
132	2023-11-14	13:23:12	detect_data_on_host()	send command: getconf LONG_BIT
133	2023-11-14	13:23:12	detect_data_on_host()	detected data: 64\n
134	2023-11-14	13:23:12	detect_os_data()	creating an OsData database record
135	2023-11-14	13:23:12	detect()	OS data detection
136	2023-11-14	13:23:12	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU op-mode(s):'
137	2023-11-14	13:23:12	detect_data_on_host()	detected data: CPU op-mode(s):                     32-bit, 64-bit\n
138	2023-11-14	13:23:12	detect_data_on_host()	send command: lscpu | grep -m 1 'Vendor ID:'
139	2023-11-14	13:23:12	detect_data_on_host()	detected data: Vendor ID:                          AuthenticAMD\n
140	2023-11-14	13:23:12	detect_data_on_host()	send command: lscpu | grep -m 1 'Model name:'
141	2023-11-14	13:23:12	detect_data_on_host()	detected data: Model name:                         AMD Ryzen 5 5600H with Radeon Graphics\n
142	2023-11-14	13:23:12	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU(s):'
143	2023-11-14	13:23:12	detect_data_on_host()	detected data: CPU(s):                             1\n
144	2023-11-14	13:23:12	detect_data_on_host()	send command: lscpu | grep -m 1 'Thread(s) per core:'
145	2023-11-14	13:23:12	detect_data_on_host()	detected data: Thread(s) per core:                 1\n
146	2023-11-14	13:23:12	detect_data_on_host()	send command: lscpu | grep -m 1 'Core(s) per socket:'
147	2023-11-14	13:23:12	detect_data_on_host()	detected data: Core(s) per socket:                 1\n
148	2023-11-14	13:23:12	detect_data_on_host()	send command: lscpu | grep -m 1 'Socket(s):'
149	2023-11-14	13:23:12	detect_data_on_host()	detected data: Socket(s):                          1\n
150	2023-11-14	13:23:12	detect_cpu_info()	creating an CpuData database record
151	2023-11-14	13:23:12	detect()	CPU data detection
152	2023-11-14	13:23:36	connection_ssh(request)	connection break
153	2023-11-14	14:05:01	connection_ssh(request)	connection break
154	2023-11-14	14:05:01	connection_ssh(request)	ssh connection to host 192.168.1.29
155	2023-11-14	14:05:01	detect_data_on_host()	send command: lsb_release -i
156	2023-11-14	14:05:01	detect_data_on_host()	detected data: Distributor ID:\tKali\n
157	2023-11-14	14:05:01	detect_data_on_host()	send command: lsb_release -d
158	2023-11-14	14:05:01	detect_data_on_host()	detected data: Description:\tKali GNU/Linux Rolling\n
159	2023-11-14	14:05:01	detect_data_on_host()	send command: lsb_release -r
160	2023-11-14	14:05:01	detect_data_on_host()	detected data: Release:\t2023.3\n
161	2023-11-14	14:05:01	detect_data_on_host()	send command: lsb_release -c
162	2023-11-14	14:05:01	detect_data_on_host()	detected data: Codename:\tkali-rolling\n
163	2023-11-14	14:05:01	detect_data_on_host()	send command: uname -m
164	2023-11-14	14:05:01	detect_data_on_host()	detected data: x86_64\n
165	2023-11-14	14:05:01	detect_data_on_host()	send command: uname -r
166	2023-11-14	14:05:01	detect_data_on_host()	detected data: 6.3.0-kali1-amd64\n
167	2023-11-14	14:05:01	detect_data_on_host()	send command: getconf LONG_BIT
168	2023-11-14	14:05:01	detect_data_on_host()	detected data: 64\n
169	2023-11-14	14:05:01	detect_os_data()	creating an OsData database record
170	2023-11-14	14:05:01	detect()	OS data detection
171	2023-11-14	14:05:01	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU op-mode(s):'
172	2023-11-14	14:05:01	detect_data_on_host()	detected data: CPU op-mode(s):                  32-bit, 64-bit\n
173	2023-11-14	14:05:02	detect_data_on_host()	send command: lscpu | grep -m 1 'Vendor ID:'
174	2023-11-14	14:05:02	detect_data_on_host()	detected data: Vendor ID:                       AuthenticAMD\n
175	2023-11-14	14:05:02	detect_data_on_host()	send command: lscpu | grep -m 1 'Model name:'
176	2023-11-14	14:05:02	detect_data_on_host()	detected data: Model name:                      AMD Ryzen 5 5600H with Radeon Graphics\n
177	2023-11-14	14:05:02	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU(s):'
178	2023-11-14	14:05:02	detect_data_on_host()	detected data: CPU(s):                          2\n
179	2023-11-14	14:05:02	detect_data_on_host()	send command: lscpu | grep -m 1 'Thread(s) per core:'
180	2023-11-14	14:05:02	detect_data_on_host()	detected data: Thread(s) per core:              1\n
181	2023-11-14	14:05:02	detect_data_on_host()	send command: lscpu | grep -m 1 'Core(s) per socket:'
182	2023-11-14	14:05:02	detect_data_on_host()	detected data: Core(s) per socket:              2\n
183	2023-11-14	14:05:02	detect_data_on_host()	send command: lscpu | grep -m 1 'Socket(s):'
184	2023-11-14	14:05:02	detect_data_on_host()	detected data: Socket(s):                       1\n
185	2023-11-14	14:05:02	detect_cpu_info()	creating an CpuData database record
186	2023-11-14	14:05:02	detect()	CPU data detection
187	2023-11-14	14:12:54	connection_ssh(request)	connection break
188	2023-11-14	14:13:01	connection_ssh(request)	connection break
189	2023-11-14	14:13:01	connection_ssh(request)	ssh connection to host 192.168.1.28
190	2023-11-14	14:13:01	detect_data_on_host()	send command: lsb_release -i
191	2023-11-14	14:13:01	detect_data_on_host()	detected data: Distributor ID:\tUbuntu\n
192	2023-11-14	14:13:01	detect_data_on_host()	send command: lsb_release -d
193	2023-11-14	14:13:01	detect_data_on_host()	detected data: Description:\tUbuntu 20.04.6 LTS\n
194	2023-11-14	14:13:01	detect_data_on_host()	send command: lsb_release -r
195	2023-11-14	14:13:01	detect_data_on_host()	detected data: Release:\t20.04\n
196	2023-11-14	14:13:01	detect_data_on_host()	send command: lsb_release -c
197	2023-11-14	14:13:01	detect_data_on_host()	detected data: Codename:\tfocal\n
198	2023-11-14	14:13:01	detect_data_on_host()	send command: uname -m
199	2023-11-14	14:13:01	detect_data_on_host()	detected data: x86_64\n
200	2023-11-14	14:13:01	detect_data_on_host()	send command: uname -r
201	2023-11-14	14:13:01	detect_data_on_host()	detected data: 5.15.0-88-generic\n
202	2023-11-14	14:13:01	detect_data_on_host()	send command: getconf LONG_BIT
203	2023-11-14	14:13:01	detect_data_on_host()	detected data: 64\n
204	2023-11-14	14:13:01	detect_os_data()	creating an OsData database record
205	2023-11-14	14:13:01	detect()	OS data detection
206	2023-11-14	14:13:01	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU op-mode(s):'
207	2023-11-14	14:13:01	detect_data_on_host()	detected data: CPU op-mode(s):                     32-bit, 64-bit\n
208	2023-11-14	14:13:01	detect_data_on_host()	send command: lscpu | grep -m 1 'Vendor ID:'
209	2023-11-14	14:13:01	detect_data_on_host()	detected data: Vendor ID:                          AuthenticAMD\n
210	2023-11-14	14:13:01	detect_data_on_host()	send command: lscpu | grep -m 1 'Model name:'
211	2023-11-14	14:13:01	detect_data_on_host()	detected data: Model name:                         AMD Ryzen 5 5600H with Radeon Graphics\n
212	2023-11-14	14:13:02	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU(s):'
213	2023-11-14	14:13:02	detect_data_on_host()	detected data: CPU(s):                             1\n
214	2023-11-14	14:13:02	detect_data_on_host()	send command: lscpu | grep -m 1 'Thread(s) per core:'
215	2023-11-14	14:13:02	detect_data_on_host()	detected data: Thread(s) per core:                 1\n
216	2023-11-14	14:13:02	detect_data_on_host()	send command: lscpu | grep -m 1 'Core(s) per socket:'
217	2023-11-14	14:13:02	detect_data_on_host()	detected data: Core(s) per socket:                 1\n
218	2023-11-14	14:13:02	detect_data_on_host()	send command: lscpu | grep -m 1 'Socket(s):'
219	2023-11-14	14:13:02	detect_data_on_host()	detected data: Socket(s):                          1\n
220	2023-11-14	14:13:02	detect_cpu_info()	creating an CpuData database record
221	2023-11-14	14:13:02	detect()	CPU data detection
222	2023-11-14	14:16:05	connection_ssh(request)	connection break
223	2023-11-14	14:16:06	connection_ssh(request)	ssh connection to host 192.168.1.28
224	2023-11-14	14:16:06	detect()	OS data detection
225	2023-11-14	14:16:06	detect_data_on_host()	send command: lsb_release -i
226	2023-11-14	14:16:06	detect_data_on_host()	detected data: Distributor ID:\tUbuntu\n
227	2023-11-14	14:16:06	detect_data_on_host()	send command: lsb_release -d
228	2023-11-14	14:16:06	detect_data_on_host()	detected data: Description:\tUbuntu 20.04.6 LTS\n
229	2023-11-14	14:16:06	detect_data_on_host()	send command: lsb_release -r
230	2023-11-14	14:16:06	detect_data_on_host()	detected data: Release:\t20.04\n
231	2023-11-14	14:16:06	detect_data_on_host()	send command: lsb_release -c
232	2023-11-14	14:16:06	detect_data_on_host()	detected data: Codename:\tfocal\n
233	2023-11-14	14:16:06	detect_data_on_host()	send command: uname -m
234	2023-11-14	14:16:06	detect_data_on_host()	detected data: x86_64\n
235	2023-11-14	14:16:06	detect_data_on_host()	send command: uname -r
236	2023-11-14	14:16:06	detect_data_on_host()	detected data: 5.15.0-88-generic\n
237	2023-11-14	14:16:06	detect_data_on_host()	send command: getconf LONG_BIT
238	2023-11-14	14:16:06	detect_data_on_host()	detected data: 64\n
239	2023-11-14	14:16:06	detect_os_data()	creating an OsData database record
240	2023-11-14	14:16:06	detect()	CPU data detection
241	2023-11-14	14:16:06	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU op-mode(s):'
242	2023-11-14	14:16:06	detect_data_on_host()	detected data: CPU op-mode(s):                     32-bit, 64-bit\n
243	2023-11-14	14:16:06	detect_data_on_host()	send command: lscpu | grep -m 1 'Vendor ID:'
244	2023-11-14	14:16:06	detect_data_on_host()	detected data: Vendor ID:                          AuthenticAMD\n
245	2023-11-14	14:16:07	detect_data_on_host()	send command: lscpu | grep -m 1 'Model name:'
246	2023-11-14	14:16:07	detect_data_on_host()	detected data: Model name:                         AMD Ryzen 5 5600H with Radeon Graphics\n
247	2023-11-14	14:16:07	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU(s):'
248	2023-11-14	14:16:07	detect_data_on_host()	detected data: CPU(s):                             1\n
249	2023-11-14	14:16:07	detect_data_on_host()	send command: lscpu | grep -m 1 'Thread(s) per core:'
250	2023-11-14	14:16:07	detect_data_on_host()	detected data: Thread(s) per core:                 1\n
251	2023-11-14	14:16:07	detect_data_on_host()	send command: lscpu | grep -m 1 'Core(s) per socket:'
252	2023-11-14	14:16:07	detect_data_on_host()	detected data: Core(s) per socket:                 1\n
253	2023-11-14	14:16:07	detect_data_on_host()	send command: lscpu | grep -m 1 'Socket(s):'
254	2023-11-14	14:16:07	detect_data_on_host()	detected data: Socket(s):                          1\n
255	2023-11-14	14:16:07	detect_cpu_info()	creating an CpuData database record
256	2023-11-14	14:18:18	close_connection()	connection break
257	2023-11-14	14:18:18	connection_ssh(request)	ssh connection to host 192.168.1.28
258	2023-11-14	14:18:18	detect()	OS data detection
259	2023-11-14	14:18:18	detect_data_on_host()	send command: lsb_release -i
260	2023-11-14	14:18:18	detect_data_on_host()	detected data: Distributor ID:\tUbuntu\n
261	2023-11-14	14:18:18	detect_data_on_host()	send command: lsb_release -d
262	2023-11-14	14:18:18	detect_data_on_host()	detected data: Description:\tUbuntu 20.04.6 LTS\n
263	2023-11-14	14:18:18	detect_data_on_host()	send command: lsb_release -r
264	2023-11-14	14:18:18	detect_data_on_host()	detected data: Release:\t20.04\n
265	2023-11-14	14:18:18	detect_data_on_host()	send command: lsb_release -c
266	2023-11-14	14:18:18	detect_data_on_host()	detected data: Codename:\tfocal\n
267	2023-11-14	14:18:19	detect_data_on_host()	send command: uname -m
268	2023-11-14	14:18:19	detect_data_on_host()	detected data: x86_64\n
269	2023-11-14	14:18:19	detect_data_on_host()	send command: uname -r
270	2023-11-14	14:18:19	detect_data_on_host()	detected data: 5.15.0-88-generic\n
271	2023-11-14	14:18:19	detect_data_on_host()	send command: getconf LONG_BIT
272	2023-11-14	14:18:19	detect_data_on_host()	detected data: 64\n
273	2023-11-14	14:18:19	detect_os_data()	creating an OsData database record
274	2023-11-14	14:18:19	detect()	CPU data detection
275	2023-11-14	14:18:19	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU op-mode(s):'
276	2023-11-14	14:18:19	detect_data_on_host()	detected data: CPU op-mode(s):                     32-bit, 64-bit\n
277	2023-11-14	14:18:19	detect_data_on_host()	send command: lscpu | grep -m 1 'Vendor ID:'
278	2023-11-14	14:18:19	detect_data_on_host()	detected data: Vendor ID:                          AuthenticAMD\n
279	2023-11-14	14:18:19	detect_data_on_host()	send command: lscpu | grep -m 1 'Model name:'
280	2023-11-14	14:18:19	detect_data_on_host()	detected data: Model name:                         AMD Ryzen 5 5600H with Radeon Graphics\n
281	2023-11-14	14:18:19	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU(s):'
282	2023-11-14	14:18:19	detect_data_on_host()	detected data: CPU(s):                             1\n
283	2023-11-14	14:18:19	detect_data_on_host()	send command: lscpu | grep -m 1 'Thread(s) per core:'
284	2023-11-14	14:18:19	detect_data_on_host()	detected data: Thread(s) per core:                 1\n
285	2023-11-14	14:18:19	detect_data_on_host()	send command: lscpu | grep -m 1 'Core(s) per socket:'
286	2023-11-14	14:18:19	detect_data_on_host()	detected data: Core(s) per socket:                 1\n
287	2023-11-14	14:18:19	detect_data_on_host()	send command: lscpu | grep -m 1 'Socket(s):'
288	2023-11-14	14:18:19	detect_data_on_host()	detected data: Socket(s):                          1\n
289	2023-11-14	14:18:19	detect_cpu_info()	creating an CpuData database record
290	2023-11-14	14:18:51	close_connection()	connection break
291	2023-11-14	14:18:57	close_connection()	connection break
292	2023-11-14	14:19:00	connection_ssh(request)	Error connecting to SSH server: Authentication failed.
293	2023-11-14	14:19:06	close_connection()	connection break
294	2023-11-14	14:19:06	connection_ssh(request)	ssh connection to host 192.168.1.28
295	2023-11-14	14:19:06	detect()	OS data detection
296	2023-11-14	14:19:06	detect_data_on_host()	send command: lsb_release -i
297	2023-11-14	14:19:06	detect_data_on_host()	detected data: Distributor ID:\tUbuntu\n
298	2023-11-14	14:19:06	detect_data_on_host()	send command: lsb_release -d
299	2023-11-14	14:19:06	detect_data_on_host()	detected data: Description:\tUbuntu 20.04.6 LTS\n
300	2023-11-14	14:19:06	detect_data_on_host()	send command: lsb_release -r
301	2023-11-14	14:19:06	detect_data_on_host()	detected data: Release:\t20.04\n
302	2023-11-14	14:19:06	detect_data_on_host()	send command: lsb_release -c
303	2023-11-14	14:19:06	detect_data_on_host()	detected data: Codename:\tfocal\n
304	2023-11-14	14:19:07	detect_data_on_host()	send command: uname -m
305	2023-11-14	14:19:07	detect_data_on_host()	detected data: x86_64\n
306	2023-11-14	14:19:07	detect_data_on_host()	send command: uname -r
307	2023-11-14	14:19:07	detect_data_on_host()	detected data: 5.15.0-88-generic\n
308	2023-11-14	14:19:07	detect_data_on_host()	send command: getconf LONG_BIT
309	2023-11-14	14:19:07	detect_data_on_host()	detected data: 64\n
310	2023-11-14	14:19:07	detect_os_data()	creating an OsData database record
311	2023-11-14	14:19:07	detect()	CPU data detection
312	2023-11-14	14:19:07	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU op-mode(s):'
313	2023-11-14	14:19:07	detect_data_on_host()	detected data: CPU op-mode(s):                     32-bit, 64-bit\n
314	2023-11-14	14:19:07	detect_data_on_host()	send command: lscpu | grep -m 1 'Vendor ID:'
315	2023-11-14	14:19:07	detect_data_on_host()	detected data: Vendor ID:                          AuthenticAMD\n
316	2023-11-14	14:19:07	detect_data_on_host()	send command: lscpu | grep -m 1 'Model name:'
317	2023-11-14	14:19:07	detect_data_on_host()	detected data: Model name:                         AMD Ryzen 5 5600H with Radeon Graphics\n
318	2023-11-14	14:19:07	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU(s):'
319	2023-11-14	14:19:07	detect_data_on_host()	detected data: CPU(s):                             1\n
320	2023-11-14	14:19:07	detect_data_on_host()	send command: lscpu | grep -m 1 'Thread(s) per core:'
321	2023-11-14	14:19:07	detect_data_on_host()	detected data: Thread(s) per core:                 1\n
322	2023-11-14	14:19:07	detect_data_on_host()	send command: lscpu | grep -m 1 'Core(s) per socket:'
323	2023-11-14	14:19:07	detect_data_on_host()	detected data: Core(s) per socket:                 1\n
324	2023-11-14	14:19:07	detect_data_on_host()	send command: lscpu | grep -m 1 'Socket(s):'
325	2023-11-14	14:19:07	detect_data_on_host()	detected data: Socket(s):                          1\n
326	2023-11-14	14:19:07	detect_cpu_info()	creating an CpuData database record
327	2023-11-14	14:19:45	close_connection()	connection break
328	2023-11-14	14:19:50	close_connection()	connection break
329	2023-11-14	14:19:53	connection_ssh(request)	Error connecting to SSH server: Authentication failed.
330	2023-11-14	14:19:59	close_connection()	connection break
331	2023-11-14	14:20:02	connection_ssh(request)	Error connecting to SSH server: Authentication failed.
332	2023-11-14	14:20:10	close_connection()	connection break
333	2023-11-14	14:20:11	connection_ssh(request)	ssh connection to host 192.168.1.28
334	2023-11-14	14:20:11	detect()	OS data detection
335	2023-11-14	14:20:11	detect_data_on_host()	send command: lsb_release -i
336	2023-11-14	14:20:11	detect_data_on_host()	detected data: Distributor ID:\tUbuntu\n
337	2023-11-14	14:20:11	detect_data_on_host()	send command: lsb_release -d
338	2023-11-14	14:20:11	detect_data_on_host()	detected data: Description:\tUbuntu 20.04.6 LTS\n
339	2023-11-14	14:20:11	detect_data_on_host()	send command: lsb_release -r
340	2023-11-14	14:20:11	detect_data_on_host()	detected data: Release:\t20.04\n
341	2023-11-14	14:20:11	detect_data_on_host()	send command: lsb_release -c
342	2023-11-14	14:20:11	detect_data_on_host()	detected data: Codename:\tfocal\n
343	2023-11-14	14:20:11	detect_data_on_host()	send command: uname -m
344	2023-11-14	14:20:11	detect_data_on_host()	detected data: x86_64\n
345	2023-11-14	14:20:11	detect_data_on_host()	send command: uname -r
346	2023-11-14	14:20:11	detect_data_on_host()	detected data: 5.15.0-88-generic\n
347	2023-11-14	14:20:11	detect_data_on_host()	send command: getconf LONG_BIT
348	2023-11-14	14:20:11	detect_data_on_host()	detected data: 64\n
349	2023-11-14	14:20:11	detect_os_data()	creating an OsData database record
350	2023-11-14	14:20:11	detect()	CPU data detection
351	2023-11-14	14:20:11	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU op-mode(s):'
352	2023-11-14	14:20:11	detect_data_on_host()	detected data: CPU op-mode(s):                     32-bit, 64-bit\n
353	2023-11-14	14:20:11	detect_data_on_host()	send command: lscpu | grep -m 1 'Vendor ID:'
354	2023-11-14	14:20:11	detect_data_on_host()	detected data: Vendor ID:                          AuthenticAMD\n
355	2023-11-14	14:20:11	detect_data_on_host()	send command: lscpu | grep -m 1 'Model name:'
356	2023-11-14	14:20:11	detect_data_on_host()	detected data: Model name:                         AMD Ryzen 5 5600H with Radeon Graphics\n
357	2023-11-14	14:20:11	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU(s):'
358	2023-11-14	14:20:11	detect_data_on_host()	detected data: CPU(s):                             1\n
359	2023-11-14	14:20:11	detect_data_on_host()	send command: lscpu | grep -m 1 'Thread(s) per core:'
360	2023-11-14	14:20:11	detect_data_on_host()	detected data: Thread(s) per core:                 1\n
361	2023-11-14	14:20:11	detect_data_on_host()	send command: lscpu | grep -m 1 'Core(s) per socket:'
362	2023-11-14	14:20:11	detect_data_on_host()	detected data: Core(s) per socket:                 1\n
363	2023-11-14	14:20:11	detect_data_on_host()	send command: lscpu | grep -m 1 'Socket(s):'
364	2023-11-14	14:20:11	detect_data_on_host()	detected data: Socket(s):                          1\n
365	2023-11-14	14:20:11	detect_cpu_info()	creating an CpuData database record
366	2023-11-14	14:22:24	close_connection()	connection break
367	2023-11-14	14:22:30	close_connection()	connection break
368	2023-11-14	14:22:33	connection_ssh(request)	Error connecting to SSH server: Authentication failed.
369	2023-11-14	14:22:38	close_connection()	connection break
370	2023-11-14	14:22:38	connection_ssh(request)	successful ssh connection to host 192.168.1.28
371	2023-11-14	14:22:38	detect()	OS data detection
372	2023-11-14	14:22:38	detect_data_on_host()	send command: lsb_release -i
373	2023-11-14	14:22:38	detect_data_on_host()	detected data: Distributor ID:\tUbuntu\n
374	2023-11-14	14:22:38	detect_data_on_host()	send command: lsb_release -d
375	2023-11-14	14:22:38	detect_data_on_host()	detected data: Description:\tUbuntu 20.04.6 LTS\n
376	2023-11-14	14:22:38	detect_data_on_host()	send command: lsb_release -r
377	2023-11-14	14:22:38	detect_data_on_host()	detected data: Release:\t20.04\n
378	2023-11-14	14:22:38	detect_data_on_host()	send command: lsb_release -c
379	2023-11-14	14:22:38	detect_data_on_host()	detected data: Codename:\tfocal\n
380	2023-11-14	14:22:38	detect_data_on_host()	send command: uname -m
381	2023-11-14	14:22:38	detect_data_on_host()	detected data: x86_64\n
382	2023-11-14	14:22:39	detect_data_on_host()	send command: uname -r
383	2023-11-14	14:22:39	detect_data_on_host()	detected data: 5.15.0-88-generic\n
384	2023-11-14	14:22:39	detect_data_on_host()	send command: getconf LONG_BIT
385	2023-11-14	14:22:39	detect_data_on_host()	detected data: 64\n
386	2023-11-14	14:22:39	detect_os_data()	creating an OsData database record
387	2023-11-14	14:22:39	detect()	CPU data detection
388	2023-11-14	14:22:39	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU op-mode(s):'
389	2023-11-14	14:22:39	detect_data_on_host()	detected data: CPU op-mode(s):                     32-bit, 64-bit\n
390	2023-11-14	14:22:39	detect_data_on_host()	send command: lscpu | grep -m 1 'Vendor ID:'
391	2023-11-14	14:22:39	detect_data_on_host()	detected data: Vendor ID:                          AuthenticAMD\n
392	2023-11-14	14:22:39	detect_data_on_host()	send command: lscpu | grep -m 1 'Model name:'
393	2023-11-14	14:22:39	detect_data_on_host()	detected data: Model name:                         AMD Ryzen 5 5600H with Radeon Graphics\n
394	2023-11-14	14:22:39	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU(s):'
395	2023-11-14	14:22:39	detect_data_on_host()	detected data: CPU(s):                             1\n
396	2023-11-14	14:22:39	detect_data_on_host()	send command: lscpu | grep -m 1 'Thread(s) per core:'
397	2023-11-14	14:22:39	detect_data_on_host()	detected data: Thread(s) per core:                 1\n
398	2023-11-14	14:22:39	detect_data_on_host()	send command: lscpu | grep -m 1 'Core(s) per socket:'
399	2023-11-14	14:22:39	detect_data_on_host()	detected data: Core(s) per socket:                 1\n
400	2023-11-14	14:22:39	detect_data_on_host()	send command: lscpu | grep -m 1 'Socket(s):'
401	2023-11-14	14:22:39	detect_data_on_host()	detected data: Socket(s):                          1\n
402	2023-11-14	14:22:39	detect_cpu_info()	creating an CpuData database record
403	2023-11-14	14:23:25	close_connection()	connection break
404	2023-11-14	14:23:35	close_connection()	connection break
405	2023-11-14	14:23:56	connection_ssh(request)	Error connecting to SSH server: [WinError 10060] Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера
406	2023-11-14	14:24:14	close_connection()	connection break
407	2023-11-14	14:24:14	connection_ssh(request)	successful ssh connection to host 192.168.1.28
408	2023-11-14	14:24:14	detect()	OS data detection
409	2023-11-14	14:24:15	detect_data_on_host()	send command: lsb_release -i
410	2023-11-14	14:24:15	detect_data_on_host()	detected data: Distributor ID:\tUbuntu\n
411	2023-11-14	14:24:15	detect_data_on_host()	send command: lsb_release -d
412	2023-11-14	14:24:15	detect_data_on_host()	detected data: Description:\tUbuntu 20.04.6 LTS\n
413	2023-11-14	14:24:15	detect_data_on_host()	send command: lsb_release -r
414	2023-11-14	14:24:15	detect_data_on_host()	detected data: Release:\t20.04\n
415	2023-11-14	14:24:15	detect_data_on_host()	send command: lsb_release -c
416	2023-11-14	14:24:15	detect_data_on_host()	detected data: Codename:\tfocal\n
417	2023-11-14	14:24:15	detect_data_on_host()	send command: uname -m
418	2023-11-14	14:24:15	detect_data_on_host()	detected data: x86_64\n
419	2023-11-14	14:24:15	detect_data_on_host()	send command: uname -r
420	2023-11-14	14:24:15	detect_data_on_host()	detected data: 5.15.0-88-generic\n
421	2023-11-14	14:24:15	detect_data_on_host()	send command: getconf LONG_BIT
422	2023-11-14	14:24:15	detect_data_on_host()	detected data: 64\n
423	2023-11-14	14:24:15	detect_os_data()	creating an OsData database record
424	2023-11-14	14:24:15	detect()	CPU data detection
425	2023-11-14	14:24:15	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU op-mode(s):'
426	2023-11-14	14:24:15	detect_data_on_host()	detected data: CPU op-mode(s):                     32-bit, 64-bit\n
427	2023-11-14	14:24:15	detect_data_on_host()	send command: lscpu | grep -m 1 'Vendor ID:'
428	2023-11-14	14:24:15	detect_data_on_host()	detected data: Vendor ID:                          AuthenticAMD\n
429	2023-11-14	14:24:15	detect_data_on_host()	send command: lscpu | grep -m 1 'Model name:'
430	2023-11-14	14:24:15	detect_data_on_host()	detected data: Model name:                         AMD Ryzen 5 5600H with Radeon Graphics\n
431	2023-11-14	14:24:15	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU(s):'
432	2023-11-14	14:24:15	detect_data_on_host()	detected data: CPU(s):                             1\n
433	2023-11-14	14:24:15	detect_data_on_host()	send command: lscpu | grep -m 1 'Thread(s) per core:'
434	2023-11-14	14:24:15	detect_data_on_host()	detected data: Thread(s) per core:                 1\n
435	2023-11-14	14:24:15	detect_data_on_host()	send command: lscpu | grep -m 1 'Core(s) per socket:'
436	2023-11-14	14:24:15	detect_data_on_host()	detected data: Core(s) per socket:                 1\n
437	2023-11-14	14:24:15	detect_data_on_host()	send command: lscpu | grep -m 1 'Socket(s):'
438	2023-11-14	14:24:15	detect_data_on_host()	detected data: Socket(s):                          1\n
439	2023-11-14	14:24:15	detect_cpu_info()	creating an CpuData database record
440	2023-11-14	22:38:25	close_connection()	connection break
441	2023-11-14	22:40:58	close_connection()	connection break
442	2023-11-14	22:40:58	connection_ssh(request)	successful ssh connection to host 192.168.1.30
443	2023-11-14	22:40:58	detect()	OS data detection
444	2023-11-14	22:40:58	detect_data_on_host()	send command: lsb_release -i
445	2023-11-14	22:40:59	detect_data_on_host()	detected data: Distributor ID:\tManjaroLinux\n
446	2023-11-14	22:40:59	detect_data_on_host()	send command: lsb_release -d
447	2023-11-14	22:40:59	detect_data_on_host()	detected data: Description:\tManjaro Linux\n
448	2023-11-14	22:40:59	detect_data_on_host()	send command: lsb_release -r
449	2023-11-14	22:40:59	detect_data_on_host()	detected data: Release:\t23.0.4\n
450	2023-11-14	22:40:59	detect_data_on_host()	send command: lsb_release -c
451	2023-11-14	22:40:59	detect_data_on_host()	detected data: Codename:\tUranos\n
452	2023-11-14	22:40:59	detect_data_on_host()	send command: uname -m
453	2023-11-14	22:40:59	detect_data_on_host()	detected data: x86_64\n
454	2023-11-14	22:40:59	detect_data_on_host()	send command: uname -r
455	2023-11-14	22:40:59	detect_data_on_host()	detected data: 6.5.5-1-MANJARO\n
456	2023-11-14	22:40:59	detect_data_on_host()	send command: getconf LONG_BIT
457	2023-11-14	22:40:59	detect_data_on_host()	detected data: 64\n
458	2023-11-14	22:40:59	detect_os_data()	creating an OsData database record
459	2023-11-14	22:40:59	detect()	CPU data detection
460	2023-11-14	22:40:59	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU op-mode(s):'
461	2023-11-14	22:40:59	detect_data_on_host()	detected data: CPU op-mode(s):                     32-bit, 64-bit\n
462	2023-11-14	22:40:59	detect_data_on_host()	send command: lscpu | grep -m 1 'Vendor ID:'
463	2023-11-14	22:40:59	detect_data_on_host()	detected data: Vendor ID:                          AuthenticAMD\n
464	2023-11-14	22:40:59	detect_data_on_host()	send command: lscpu | grep -m 1 'Model name:'
465	2023-11-14	22:40:59	detect_data_on_host()	detected data: Model name:                         AMD Ryzen 5 5600H with Radeon Graphics\n
466	2023-11-14	22:40:59	detect_data_on_host()	send command: lscpu | grep -m 1 'CPU(s):'
467	2023-11-14	22:40:59	detect_data_on_host()	detected data: CPU(s):                             1\n
468	2023-11-14	22:40:59	detect_data_on_host()	send command: lscpu | grep -m 1 'Thread(s) per core:'
469	2023-11-14	22:40:59	detect_data_on_host()	detected data: Thread(s) per core:                 1\n
470	2023-11-14	22:40:59	detect_data_on_host()	send command: lscpu | grep -m 1 'Core(s) per socket:'
471	2023-11-14	22:40:59	detect_data_on_host()	detected data: Core(s) per socket:                 1\n
472	2023-11-14	22:40:59	detect_data_on_host()	send command: lscpu | grep -m 1 'Socket(s):'
473	2023-11-14	22:40:59	detect_data_on_host()	detected data: Socket(s):                          1\n
474	2023-11-14	22:40:59	detect_cpu_info()	creating an CpuData database record
\.


--
-- TOC entry 4921 (class 0 OID 16635)
-- Dependencies: 237
-- Data for Name: patrol_osdata; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.patrol_osdata (id, "OS", description, release, codename, architecture, kernel, type) FROM stdin;
1	Ubuntu	Ubuntu 20.04.6 LTS	20.04	focal	x86_64	5.15.0-88-generic	64
2	Kali	Kali GNU/Linux Rolling	2023.3	kali-rolling	x86_64	6.3.0-kali1-amd64	64
3	Ubuntu	Ubuntu 20.04.6 LTS	20.04	focal	x86_64	5.15.0-88-generic	64
4	Ubuntu	Ubuntu 20.04.6 LTS	20.04	focal	x86_64	5.15.0-88-generic	64
5	Ubuntu	Ubuntu 20.04.6 LTS	20.04	focal	x86_64	5.15.0-88-generic	64
6	Ubuntu	Ubuntu 20.04.6 LTS	20.04	focal	x86_64	5.15.0-88-generic	64
7	Ubuntu	Ubuntu 20.04.6 LTS	20.04	focal	x86_64	5.15.0-88-generic	64
8	Ubuntu	Ubuntu 20.04.6 LTS	20.04	focal	x86_64	5.15.0-88-generic	64
9	Ubuntu	Ubuntu 20.04.6 LTS	20.04	focal	x86_64	5.15.0-88-generic	64
10	ManjaroLinux	Manjaro Linux	23.0.4	Uranos	x86_64	6.5.5-1-MANJARO	64
\.


--
-- TOC entry 4929 (class 0 OID 0)
-- Dependencies: 221
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 4930 (class 0 OID 0)
-- Dependencies: 223
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 4931 (class 0 OID 0)
-- Dependencies: 219
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 60, true);


--
-- TOC entry 4932 (class 0 OID 0)
-- Dependencies: 227
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- TOC entry 4933 (class 0 OID 0)
-- Dependencies: 225
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- TOC entry 4934 (class 0 OID 0)
-- Dependencies: 229
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- TOC entry 4935 (class 0 OID 0)
-- Dependencies: 231
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- TOC entry 4936 (class 0 OID 0)
-- Dependencies: 217
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 15, true);


--
-- TOC entry 4937 (class 0 OID 0)
-- Dependencies: 215
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 27, true);


--
-- TOC entry 4938 (class 0 OID 0)
-- Dependencies: 234
-- Name: patrol_cpudata_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.patrol_cpudata_id_seq', 10, true);


--
-- TOC entry 4939 (class 0 OID 0)
-- Dependencies: 238
-- Name: patrol_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.patrol_logs_id_seq', 474, true);


--
-- TOC entry 4940 (class 0 OID 0)
-- Dependencies: 236
-- Name: patrol_osdata_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.patrol_osdata_id_seq', 10, true);


--
-- TOC entry 4707 (class 2606 OID 16534)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4712 (class 2606 OID 16465)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4715 (class 2606 OID 16434)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4709 (class 2606 OID 16426)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4702 (class 2606 OID 16456)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4704 (class 2606 OID 16420)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4723 (class 2606 OID 16448)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4726 (class 2606 OID 16480)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 4717 (class 2606 OID 16440)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4729 (class 2606 OID 16454)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4732 (class 2606 OID 16494)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 4720 (class 2606 OID 16529)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 4735 (class 2606 OID 16515)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4697 (class 2606 OID 16414)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4699 (class 2606 OID 16412)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4695 (class 2606 OID 16406)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4739 (class 2606 OID 16542)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 4742 (class 2606 OID 16633)
-- Name: patrol_cpudata patrol_cpudata_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.patrol_cpudata
    ADD CONSTRAINT patrol_cpudata_pkey PRIMARY KEY (id);


--
-- TOC entry 4746 (class 2606 OID 16649)
-- Name: patrol_logs patrol_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.patrol_logs
    ADD CONSTRAINT patrol_logs_pkey PRIMARY KEY (id);


--
-- TOC entry 4744 (class 2606 OID 16641)
-- Name: patrol_osdata patrol_osdata_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.patrol_osdata
    ADD CONSTRAINT patrol_osdata_pkey PRIMARY KEY (id);


--
-- TOC entry 4705 (class 1259 OID 16535)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4710 (class 1259 OID 16476)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4713 (class 1259 OID 16477)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4700 (class 1259 OID 16462)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 4721 (class 1259 OID 16492)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 4724 (class 1259 OID 16491)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 4727 (class 1259 OID 16506)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 4730 (class 1259 OID 16505)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 4718 (class 1259 OID 16530)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 4733 (class 1259 OID 16526)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 4736 (class 1259 OID 16527)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 4737 (class 1259 OID 16544)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 4740 (class 1259 OID 16543)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 4748 (class 2606 OID 16471)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4749 (class 2606 OID 16466)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4747 (class 2606 OID 16457)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4750 (class 2606 OID 16486)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4751 (class 2606 OID 16481)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4752 (class 2606 OID 16500)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4753 (class 2606 OID 16495)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4754 (class 2606 OID 16516)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4755 (class 2606 OID 16521)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2023-11-15 00:04:46

--
-- PostgreSQL database dump complete
--

