# Generated by Django 4.2.7 on 2023-11-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpuData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modes', models.CharField()),
                ('vendor', models.CharField()),
                ('model', models.CharField()),
                ('CPUs', models.CharField()),
                ('threads', models.CharField()),
                ('cores_per_socket', models.CharField()),
                ('sockets', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='OsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OS', models.CharField()),
                ('description', models.CharField()),
                ('release', models.CharField()),
                ('codename', models.CharField()),
                ('architecture', models.CharField()),
                ('kernel', models.CharField()),
                ('type', models.CharField()),
            ],
        ),
    ]
