# Generated by Django 4.2.7 on 2023-11-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrol', '0002_cpudata_osdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('function', models.CharField()),
                ('event', models.CharField()),
            ],
        ),
    ]
